
version: '2'

networks: 
    default:

services:

  nginx:
    image: nginx
    volumes:
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
        - "80:80"

  nextbus:
    build: ./
    networks:
      default:
        aliases:
           - backend
    ports:
      - "8080"

  redis:
    image: gcr.io/google_containers/redis:e2e
